### ISSUE TITLE
Js-Tree : bug élément sans enfants affiché comme si il en avait

### ISSUE THREAD

**Issue by gbrousse-recia** [GIP-RECIA/esup-publisher-webcomponents#16]
![js-tree-bug-childs](https://user-images.githubusercontent.com/93128808/161081473-17fae03e-dd67-4d8d-9f3d-e60d94961495.png)

**Comment by jgribonvald** [comment]
@gbrousse-recia on ne pourra pas changer ce comportement, car on ne peut pas savoir s'il y a des enfant tant qu'on n'a pas fait la requête. En fait cette partie se cache après avoir fait la requête et s'il n'y a pas d'enfants

**Comment by gbrousse-recia** [comment]
@jgribonvald Ok, mais du coup pourquoi ne pas précharger la liste des enfants à l'affichage du parent ?

**Comment by jgribonvald** [comment]
car certaines requêtes sont lourdes de conséquences, c'est une volontée pour limité l'impacte.
